language: node_js
node_js:
- '6.5.0'
branches:
  only:
  - master                # 只监测 source 分支上的 commit
before_install:
- npm install -g hexo-cli # 安装 hexo
install:
- npm install             # 安装额外的插件

script:
#- git submodule init      # 用于更新主题
#- git submodule update
- hexo clean && hexo generate
#- hexo s
after_success:
  - cd ./public
  - git init
  - git config user.name "caiwangwhu"
  - git config user.email "799027612@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
env:
 global:
   - GH_REF: github.com/caiwangwhu/caiwangwhu.github.io.git
